name = "Bone"
description = "Bone"

ambient = 1.0
diffuse = 1.0
specular = 0.0

[[transfer_functions]]

[transfer_functions.opacity]
[[transfer_functions.opacity.points]]
x = -1024.0
y = 0.0

[[transfer_functions.opacity.points]]
x = 54.0
y = 0.0

[[transfer_functions.opacity.points]]
x = 536.0
y = 0.1

[[transfer_functions.opacity.points]]
x = 3071.0
y = 0.1

[transfer_functions.color]
[[transfer_functions.color.points]]
x = -1024.0
r = 0.0
g = 0.0
b = 0.0

[[transfer_functions.color.points]]
x = 54.0
r = 0.0
g = 0.0
b = 0.0

[[transfer_functions.color.points]]
x = 536.0
r = 1.0
g = 1.0
b = 1.0

[[transfer_functions.color.points]]
x = 3071.0
r = 1.0
g = 1.0
b = 1.0
