name = "Vascular_Closed"
description = "Vascular (Closed)"

ambient = 0.7
diffuse = 0.4
specular = 1.0

[[transfer_functions]]

[transfer_functions.opacity]
[[transfer_functions.opacity.points]]
x = 150
y = 0.0

[[transfer_functions.opacity.points]]
x = 650
y = 1.0

[[transfer_functions.opacity.points]]
x = 3071
y = 1.0

[transfer_functions.color]
[[transfer_functions.color.points]]
x = 150
r = 1.0
g = 1.0
b = 1.0

[[transfer_functions.color.points]]
x = 3071
r = 1.0
g = 1.0
b = 1.0

[[transfer_functions]]

[transfer_functions.opacity]
[[transfer_functions.opacity.points]]
x = -96.5
y = 0.0

[[transfer_functions.opacity.points]]
x = 269.0
y = 0.05

[[transfer_functions.opacity.points]]
x = 474.5
y = 0.0

[transfer_functions.color]
[[transfer_functions.color.points]]
x = -96.5
r = 1.0
g = 1.0
b = 1.0

[[transfer_functions.color.points]]
x = 474.5
r = 1.0
g = 1.0
b = 1.0

[[transfer_functions]]

[transfer_functions.opacity]
[[transfer_functions.opacity.points]]
x = 120
y = 0.0

[[transfer_functions.opacity.points]]
x = 258.0
y = 0.8

[[transfer_functions.opacity.points]]
x = 320
y = 0.0

[transfer_functions.color]
[[transfer_functions.color.points]]
x = 120
r = 1.0
g = 0.0
b = 0.0

[[transfer_functions.color.points]]
x = 320
r = 1.0
g = 1.0
b = 0.0
