current_frame = 0
screenshot_directory = "./data/screenshots"
screenshot_subdirectory_format = "%Y-%m-%d-%H-%M-%S"
rotation_factor = 3

[background]
light = [1.0, 1.0, 1.0]
dark = [0.0, 0.0, 0.0]

[[meshes]]
label = "BL_Dense"
directory = "./data/obj-bl-dense"
visible = true
loop_subdivision_iterations = 1

[meshes.property]
representation = 2
r = 1.0
g = 0.0
b = 0.0
edge_visibility = false
vertex_visibility = false
shading = true
interpolation = 1

[[meshes]]
label = "BL_Simplified"
directory = "./data/obj-bl"
visible = true

[meshes.property]
representation = 2
r = 1.0
g = 0.5
b = 0.5
edge_visibility = true
vertex_visibility = false
shading = false
interpolation = 0

[[volumes]]
label="BL"
directory="./data/img-bl"
visible=true
transfer_function_preset="vascular_closed"
clipping_enabled=true
