[metadata]
coordinate_system = "LPS"
axis_convention = "itk"
units = "radians"
timestamp = "2026-01-16T20:45:18.134420"
volume_label = "CCTA"

[mpr_origin]
x = 33.44902373904834
y = -188.86967328159682
z = -129.89202591668126

[[angles_list]]
axes = "Z"
angle = 0.578407346410207
visible = true
name = "vla"
name_editable = false
deletable = false

[[angles_list]]
axes = "X"
angle = -0.821592653589793
visible = true
name = "vla_2_sax"
name_editable = false
deletable = false

[[angles_list]]
axes = "Z"
angle = 1.948407346410207
visible = true
name = "sax_2_2ch"
name_editable = false
deletable = false

[[angles_list]]
axes = "Z"
angle = 1.018407346410207
visible = false
name = "sax_2_3ch"
name_editable = false
deletable = false

[[angles_list]]
axes = "Z"
angle = -0.361592653589793
visible = false
name = "sax_2_4ch"
name_editable = false
deletable = false
