mpr_origin = [-129.89202591668126, -188.86967328159682, 33.44902373904834]

[metadata]
coordinate_system = "LPS"
index_order = "roma"
angle_units = "degrees"
timestamp = "2026-01-17T09:57:14.224189"
volume_label = "CCTA"

[[angles_list]]
axes = "X"
angle = -33.14029978866625
visible = true
name = "vla"
name_editable = false
deletable = false

[[angles_list]]
axes = "Z"
angle = 47.07379152964901
visible = true
name = "vla_2_sax"
name_editable = false
deletable = false

[[angles_list]]
axes = "X"
angle = -111.63551772158903
visible = true
name = "sax_2_2ch"
name_editable = false
deletable = false

[[angles_list]]
axes = "X"
angle = -58.35044277442247
visible = false
name = "sax_2_3ch"
name_editable = false
deletable = false

[[angles_list]]
axes = "X"
angle = 20.717732953631135
visible = false
name = "sax_2_4ch"
name_editable = false
deletable = false
